version: '3.1'

services:
  mysql:
    image: mysql:8.0.21
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: "fun_docker"
      MYSQL_USER: "fun_docker"
      MYSQL_PASSWORD: "fun_docker"
#    volumes:
#    - mysql_data:/var/lib/mysql ##if wanting to persist state
    ports:
      - 3307:3306 #toLocal:inContainer
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
  fun-docker:
    image: com.lsq/real-world-application:0.1
    restart: always
    depends_on:
      - mysql
    ports:
      - 8080:8080
      - 4000:4000
#volumes:
#  mysql_data: