version: '3.1'

services:
  mysql:
    image: mysql:8.0.21
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: "fun_docker"
      MYSQL_USER: "fun_docker"
      MYSQL_PASSWORD: "fun_docker"
    ports:
      - 3307:3306
  fun-docker:
    image: com.lsq/real-world-application:0.1
    restart: always
    depends_on:
      - mysql
    ports:
      - 8080:8080
      - 4000:4000